services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=${DATABASE_NAME:-tv_tracker}'
      - 'POSTGRES_PASSWORD=${DATABASE_PASSWORD:-postgres}'
      - 'POSTGRES_USER=${DATABASE_USERNAME:-postgres}'
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data