spring:
  application:
    name: tv-show-tracker
  jpa:
    show-sql: true
  graphql:
    graphiql:
      enabled: true
    schema:
      introspection:
        enabled: true
  datasource:
    url: "jdbc:postgresql://localhost:5432/${DATABASE_NAME:tv_tracker}_dev"
    username: "${DATABASE_USERNAME:postgres}"
    password: "${DATABASE_PASSWORD:postgres}"
  docker:
    compose:
      file:
        - "compose.yaml"
  mail:
    host: "${SMTP_HOST:smtp.hostinger.com}"
    port: "${SMTP_POST:587}"
    username: "${SMTP_EMAIL:tekever@acehq.net}"
    password: "${SMTP_PASSWORD:}"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: false
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
app:
  frontend:
    url: "${FRONTEND_URL:http://localhost:3000}"
  discovery:
    enabled: "${DISCOVERY_ENABLED:true}"
  db:
    name: "${DATABASE_NAME:tv_tracker}_dev"
    max-size: "${DATABASE_MAX_SIZE:9}"
  jwt:
    secret: "${JWT_SECRET:}"
    access-token:
      duration: "${JWT_ACCESS_TOKEN_DURATION:10080}"
    refresh-token:
      duration: "${JWT_REFRESH_TOKEN_DURATION:10080}"
    cookie:
      domain: "${JWT_COOKIE_DOMAIN:localhost}"
      secure: false
tmdb:
  api-key: "${TMDB_API_KEY}"
resilience4j:
  ratelimiter:
    metrics:
      enabled: true
    instances:
      rateLimiterApi:
        register-health-indicator: true
        limit-for-period: 25
        limit-refresh-period: 2s
        timeout-duration: 2s
        allow-health-indicator-to-fail: true
        subscribe-for-events: true
        event-consumer-buffer-size: 200